# Generated by Django 6.0 on 2025-12-12 14:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sermon_date', models.DateField()),
                ('sermon_type', models.CharField(choices=[('sunday', 'Sunday Service'), ('midweek', 'Midweek Service'), ('special', 'Special Service'), ('seminar', 'Seminar/Teaching')], default='sunday', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('full_notes', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/audio/')),
                ('video_url', models.URLField(blank=True)),
                ('slides_file', models.FileField(blank=True, null=True, upload_to='sermons/slides/')),
                ('handout_file', models.FileField(blank=True, null=True, upload_to='sermons/handouts/')),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('attendance_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons_preached', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sermon_date'],
            },
        ),
    ]
