# Generated by Django 6.0 on 2025-12-15 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-sermon_date'], 'permissions': [('can_manage_sermons', 'Can manage sermons'), ('can_upload_sermons', 'Can upload sermons')], 'verbose_name': 'Sermon', 'verbose_name_plural': 'Sermons'},
        ),
        migrations.AddField(
            model_name='sermon',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sermon',
            name='guest_speaker_name',
            field=models.CharField(blank=True, help_text='name of the guest speaker (If not a registered member)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='scripture_reference',
            field=models.TextField(blank=True, help_text='eg .. John 3:16, Genesis 1-1-5, Psalm 23', null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='series',
            field=models.CharField(blank=True, help_text='Sermon series name (if part of a series)', max_length=100),
        ),
        migrations.AddField(
            model_name='sermon',
            name='series_part',
            field=models.IntegerField(blank=True, help_text='Part number in the series', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sermon',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the sermon', null=True, upload_to='sermons/thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='attendance_count',
            field=models.IntegerField(blank=True, help_text='Number of people in attendance', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload audio file (MP3, WAV, etc.)', null=True, upload_to='sermons/audio/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='full_notes',
            field=models.TextField(blank=True, help_text='Full sermon notes or transcript'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='handout_file',
            field=models.FileField(blank=True, help_text='Upload handout (PDF, Word, etc.)', null=True, upload_to='sermons/handouts/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='preacher',
            field=models.ForeignKey(blank=True, help_text='Select a registered church member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons_preached', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='sermon_type',
            field=models.CharField(choices=[('sunday', 'Sunday Service'), ('midweek', 'Midweek Service'), ('special', 'Special Service'), ('seminar', 'Seminar/Teaching'), ('conference', 'Conference')], default='sunday', max_length=20),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='slides_file',
            field=models.FileField(blank=True, help_text='Upload presentation slides (PDF, PPT, etc.)', null=True, upload_to='sermons/slides/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief summary of the sermon (for display)'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., love, forgiveness, faith)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(help_text='Title of the sermon', max_length=200),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to video (YouTube, Vimeo, etc.)'),
        ),
    ]
