# Generated by Django 6.0 on 2025-12-16 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_userrole_valid_from_alter_userrole_valid_to'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='responsible_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='groups.churchgroup'),
        ),
        migrations.DeleteModel(
            name='ChurchGroup',
        ),
    ]
