# Generated by Django 6.0 on 2025-12-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_responsible_group_delete_churchgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost for this task', max_digits=10),
        ),
    ]
