# Generated by Django 6.0 on 2025-12-12 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='groups.churchgroup'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_members',
            field=models.ManyToManyField(blank=True, related_name='personal_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
