# Generated by Django 6.0 on 2025-12-12 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group_type', models.CharField(choices=[('men', "Men's Fellowship"), ('women', "Women's Fellowship"), ('youth', 'Youth Group'), ('sunday_school', 'Sunday School'), ('choir', 'Choir'), ('prayer', 'Prayer Group'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leaders', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='leading_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('church_admin', 'Church Admin'), ('sub_admin', 'Sub Admin'), ('group_leader', 'Group Leader'), ('teacher', 'Sunday School Teacher'), ('member', 'Member')], default='member', max_length=100)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('can_manage_events', models.BooleanField(default=False)),
                ('can_manage_finances', models.BooleanField(default=False)),
                ('can_send_announcements', models.BooleanField(default=False)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(auto_now=True)),
                ('assigned_groups', models.ManyToManyField(blank=True, related_name='assigned_roles', to='groups.churchgroup')),
                ('permissions_granted', models.ManyToManyField(blank=True, to='auth.permission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='church_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=120, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='groups.churchgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'date_joined'],
                'unique_together': {('member', 'group')},
            },
        ),
    ]
