# Generated by Django 6.0 on 2025-12-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
