# Generated by Django 6.0 on 2025-12-12 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('objective', models.TextField()),
                ('scripture_reference', models.CharField(max_length=100)),
                ('teacher_guide', models.TextField(blank=True)),
                ('student_materials', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('discussion_questions', models.TextField(blank=True)),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to='lessons/presentations/%Y/%m/')),
                ('handout_file', models.FileField(blank=True, null=True, upload_to='lessons/handouts/%Y/%m/')),
                ('audio_video', models.FileField(blank=True, null=True, upload_to='lessons/media/%Y/%m/')),
                ('date_taught', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['curriculum', 'lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('curriculum_type', models.CharField(choices=[('sunday_school', 'Sunday School'), ('bible_study', 'Bible Study'), ('discipleship', 'Discipleship'), ('training', 'Training')], max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_lessons', models.IntegerField(default=1)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='curriculum/resources/%Y/%m/')),
                ('external_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
