# Generated by Django 6.0 on 2025-12-17 10:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
        ('groups', '0002_alter_userrole_valid_from_alter_userrole_valid_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Curriculum Progress',
                'verbose_name_plural': 'Curriculum Progress Records',
            },
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Any observations')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lesson Attendance',
                'verbose_name_plural': 'Lesson Attendances',
            },
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['-start_date', 'title'], 'verbose_name_plural': 'Curricula'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['curriculum', 'lesson_number'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AddField(
            model_name='curriculum',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this curriculum', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_curriculums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='additional_files',
            field=models.FileField(blank=True, help_text='Additional resources', null=True, upload_to='lessons/additional/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='attendance_count',
            field=models.IntegerField(default=0, help_text='Number of attendees', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Lesson conclusion'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='estimated_duration',
            field=models.IntegerField(default=60, help_text='Estimated duration in minutes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='introduction',
            field=models.TextField(blank=True, help_text='Lesson introduction'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curriculums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_type',
            field=models.CharField(choices=[('sunday_school', 'Sunday School'), ('bible_study', 'Bible Study'), ('discipleship', 'Discipleship'), ('training', 'Training'), ('new_members', 'New Members Class'), ('leadership', 'Leadership Training')], max_length=100),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to external resource'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Main curriculum file (PDF, Word, etc.)', null=True, upload_to='curriculum/resources/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='target_group',
            field=models.ForeignKey(help_text='Group this curriculum is designed for', on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='groups.churchgroup'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='total_lessons',
            field=models.IntegerField(default=1, help_text='Total number of lessons in this curriculum', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='activities',
            field=models.TextField(blank=True, help_text='Classroom activities'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio_video',
            field=models.FileField(blank=True, help_text='Audio or video lesson', null=True, upload_to='lessons/media/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_taught',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='discussion_questions',
            field=models.TextField(blank=True, help_text='Discussion questions'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='handout_file',
            field=models.FileField(blank=True, help_text='Printable handouts', null=True, upload_to='lessons/handouts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.IntegerField(help_text='Lesson number in sequence', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='objective',
            field=models.TextField(help_text='Learning objective for this lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='presentation_file',
            field=models.FileField(blank=True, help_text='Presentation slides (PPT, PDF)', null=True, upload_to='lessons/presentations/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='scripture_reference',
            field=models.CharField(help_text='Bible reference (e.g., John 3:16)', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student_materials',
            field=models.TextField(blank=True, help_text='Student materials'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher_guide',
            field=models.TextField(blank=True, help_text="Teacher's guide"),
        ),
        migrations.AddIndex(
            model_name='curriculum',
            index=models.Index(fields=['status', 'start_date'], name='curriculum__status_676947_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculum',
            index=models.Index(fields=['curriculum_type', 'target_group'], name='curriculum__curricu_be99eb_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['curriculum', 'date_taught'], name='curriculum__curricu_36b12d_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'date_taught'], name='curriculum__teacher_41f6c5_idx'),
        ),
        migrations.AddField(
            model_name='curriculumprogress',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='progress_completed', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='curriculumprogress',
            name='current_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_current', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='curriculumprogress',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='curriculum.curriculum'),
        ),
        migrations.AddField(
            model_name='curriculumprogress',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonattendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='lessonattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonattendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumprogress',
            unique_together={('curriculum', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonattendance',
            unique_together={('lesson', 'member')},
        ),
    ]
